# ─────────────────────────────────────────────────────────────────────────────
# Sentiment Analysis API — Chainguard PyTorch
#
# Two-stage build:
#   builder  — installs extra Python deps on top of the PyTorch base.
#              The Chainguard PyTorch image already has torch installed, so pip
#              will not reinstall it — only the extra packages land in /deps.
#   runtime  — copies those extra packages into a fresh image. PyTorch comes
#              from the base; transformers/fastapi come from the builder copy.
#
# NOTE: Both stages use :latest-dev because the demo requires pip (to install
# deps) at build time, and wget (for Docker's healthcheck) at runtime.
# In a production hardening pass, switch the runtime to :latest and bake
# wget into a custom layer, or use a TCP healthcheck instead.
# ─────────────────────────────────────────────────────────────────────────────

# ── Stage 1: dependency installation + model pre-fetch ───────────────────────
FROM cgr.dev/chainguard/pytorch:latest-dev AS builder

WORKDIR /build

# Install only the extra packages — torch is already present in the base image
# so pip skips it, keeping /deps small (~300 MB vs ~2 GB with torch).
COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/deps -r requirements.txt

# Pre-download the model weights at build time.
# Baking them into the image means:
#   • Zero network calls at container startup (TRANSFORMERS_OFFLINE=1 at runtime)
#   • Deterministic, reproducible inference — the model is part of the image digest
#   • The SBOM generated by Syft will capture the model files
ENV HF_HOME=/model-cache
COPY prefetch_model.py .
RUN python prefetch_model.py

# ── Stage 2: runtime ──────────────────────────────────────────────────────────
FROM cgr.dev/chainguard/pytorch:latest-dev

WORKDIR /app

# Add the extra pip packages on top of the base PyTorch installation
COPY --from=builder /deps/lib /usr/local/lib
COPY --from=builder /deps/bin /usr/local/bin

# Copy the pre-fetched model cache — no downloads at startup
COPY --from=builder /model-cache /model-cache

# Copy application last — changes here only invalidate this thin layer
COPY main.py .

# Tell transformers to load from the baked-in cache (no network required)
ENV HF_HOME=/model-cache \
    TRANSFORMERS_OFFLINE=1

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
